-- Execute este script no SQL Editor do seu painel do Supabase

-- 1. Tabelas de Domínio
CREATE TABLE IF NOT EXISTS oms (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome TEXT UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS funcoes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome TEXT UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS conhecimentos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome TEXT UNIQUE NOT NULL
);

-- 2. Tabela de Usuários
CREATE TABLE IF NOT EXISTS usuarios (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome TEXT NOT NULL,
  nome_completo TEXT,
  posto_graduacao TEXT,
  codigo_interno TEXT UNIQUE NOT NULL,
  organizacao_militar TEXT,
  ramal TEXT,
  foto_perfil TEXT,
  funcao TEXT,
  conhecimento_material TEXT,
  perfil TEXT DEFAULT 'usuario',
  ativo BOOLEAN DEFAULT true,
  data_cadastro TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Consultas e Comentários
CREATE TABLE IF NOT EXISTS consultas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id BIGINT REFERENCES usuarios(id) ON DELETE CASCADE,
  numero_item TEXT NOT NULL,
  nome_item TEXT NOT NULL,
  classificacao TEXT,
  meio_operacional TEXT,
  descricao TEXT NOT NULL,
  status TEXT DEFAULT 'aberto',
  arquivo_url TEXT,
  data_criacao TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS comentarios (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  consulta_id BIGINT REFERENCES consultas(id) ON DELETE CASCADE,
  usuario_id BIGINT REFERENCES usuarios(id) ON DELETE CASCADE,
  texto TEXT NOT NULL,
  arquivo_url TEXT,
  data_criacao TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. Interações (Curtidas)
CREATE TABLE IF NOT EXISTS curtidas_consultas (
  consulta_id BIGINT REFERENCES consultas(id) ON DELETE CASCADE,
  usuario_id BIGINT REFERENCES usuarios(id) ON DELETE CASCADE,
  PRIMARY KEY (consulta_id, usuario_id)
);

CREATE TABLE IF NOT EXISTS curtidas_comentarios (
  comentario_id BIGINT REFERENCES comentarios(id) ON DELETE CASCADE,
  usuario_id BIGINT REFERENCES usuarios(id) ON DELETE CASCADE,
  PRIMARY KEY (comentario_id, usuario_id)
);

-- 5. Empresas e Validações
CREATE TABLE IF NOT EXISTS empresas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cnpj TEXT UNIQUE NOT NULL,
  razao_social TEXT NOT NULL,
  telefones TEXT,
  emails TEXT,
  tipo TEXT,
  numero_item TEXT,
  indicado_por_id BIGINT REFERENCES usuarios(id) ON DELETE SET NULL,
  data_cadastro TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS validacoes_empresas (
  empresa_id BIGINT REFERENCES empresas(id) ON DELETE CASCADE,
  usuario_id BIGINT REFERENCES usuarios(id) ON DELETE CASCADE,
  data_validacao TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  PRIMARY KEY (empresa_id, usuario_id)
);

-- 6. Social e Chat
CREATE TABLE IF NOT EXISTS amizades (
  usuario_id BIGINT REFERENCES usuarios(id) ON DELETE CASCADE,
  amigo_id BIGINT REFERENCES usuarios(id) ON DELETE CASCADE,
  data_amizade TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  PRIMARY KEY (usuario_id, amigo_id)
);

CREATE TABLE IF NOT EXISTS notificacoes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id BIGINT REFERENCES usuarios(id) ON DELETE CASCADE,
  tipo TEXT NOT NULL,
  mensagem TEXT NOT NULL,
  link TEXT,
  lida BOOLEAN DEFAULT false,
  data_criacao TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS conversas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario1_id BIGINT REFERENCES usuarios(id) ON DELETE CASCADE,
  usuario2_id BIGINT REFERENCES usuarios(id) ON DELETE CASCADE,
  data_criacao TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  data_ultima_mensagem TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE(usuario1_id, usuario2_id)
);

CREATE TABLE IF NOT EXISTS mensagens_chat (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conversa_id BIGINT REFERENCES conversas(id) ON DELETE CASCADE,
  remetente_id BIGINT REFERENCES usuarios(id) ON DELETE CASCADE,
  texto TEXT NOT NULL,
  arquivo_url TEXT,
  lida BOOLEAN DEFAULT false,
  data_envio TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 7. Auditoria
CREATE TABLE IF NOT EXISTS auditoria (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id BIGINT REFERENCES usuarios(id) ON DELETE SET NULL,
  acao TEXT NOT NULL,
  descricao TEXT,
  objeto_afetado TEXT,
  data_hora TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Configuração de Storage (Buckets)
-- Execute isso no SQL Editor ou crie manualmente na interface do Supabase em "Storage"
INSERT INTO storage.buckets (id, name, public) VALUES ('arquivos', 'arquivos', true) ON CONFLICT DO NOTHING;
INSERT INTO storage.buckets (id, name, public) VALUES ('avatares', 'avatares', true) ON CONFLICT DO NOTHING;

-- Políticas de Segurança (RLS) - Permitindo acesso público para facilitar a migração inicial
-- Em produção, você deve restringir isso
ALTER TABLE usuarios ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Permitir tudo para usuarios" ON usuarios FOR ALL USING (true);

ALTER TABLE consultas ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Permitir tudo para consultas" ON consultas FOR ALL USING (true);

ALTER TABLE comentarios ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Permitir tudo para comentarios" ON comentarios FOR ALL USING (true);

ALTER TABLE empresas ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Permitir tudo para empresas" ON empresas FOR ALL USING (true);

-- (Repita para outras tabelas conforme necessário ou desative o RLS temporariamente)
