-- Execute este script no SQL Editor do Supabase para habilitar o modulo RFQ

CREATE TABLE IF NOT EXISTS rfq_companies (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  cnpj TEXT UNIQUE,
  email TEXT NOT NULL,
  contact_name TEXT,
  segment TEXT,
  rating NUMERIC(4,2) DEFAULT 0,
  status TEXT NOT NULL DEFAULT 'Pending' CHECK (status IN ('Approved', 'Pending')),
  lead_time_days INTEGER DEFAULT 0,
  last_rfq DATE,
  preferred_categories JSONB DEFAULT '[]'::jsonb,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS rfq_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sku TEXT UNIQUE NOT NULL,
  description TEXT NOT NULL,
  category TEXT NOT NULL,
  annual_volume INTEGER DEFAULT 0,
  unit TEXT DEFAULT 'un',
  preferred_supplier TEXT,
  last_valid_price NUMERIC(14,2),
  last_valid_date DATE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS rfq_processes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  buyer_name TEXT NOT NULL,
  created_by_user_id BIGINT REFERENCES usuarios(id) ON DELETE SET NULL,
  primary_company_name TEXT,
  department TEXT,
  deadline DATE NOT NULL,
  status TEXT NOT NULL DEFAULT 'Draft' CHECK (status IN ('Draft', 'Open', 'In Review', 'Negotiation', 'Closed', 'Awarded')),
  savings_potential NUMERIC(8,2) DEFAULT 0,
  risk_level TEXT NOT NULL DEFAULT 'Medium' CHECK (risk_level IN ('Low', 'Medium', 'High')),
  input_mode TEXT NOT NULL DEFAULT 'Manual' CHECK (input_mode IN ('Manual', 'Spreadsheet')),
  total_items INTEGER DEFAULT 0,
  winning_supplier_company_id BIGINT REFERENCES rfq_companies(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  closed_at TIMESTAMPTZ,
  validity_until DATE
);

CREATE TABLE IF NOT EXISTS rfq_process_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  process_id BIGINT NOT NULL REFERENCES rfq_processes(id) ON DELETE CASCADE,
  sku TEXT NOT NULL,
  description TEXT NOT NULL,
  quantity NUMERIC(14,2) DEFAULT 0,
  unit TEXT DEFAULT 'un',
  target_price NUMERIC(14,2) DEFAULT 0,
  preferred_supplier TEXT,
  historical_reference TEXT
);

CREATE TABLE IF NOT EXISTS rfq_invitations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  process_id BIGINT NOT NULL REFERENCES rfq_processes(id) ON DELETE CASCADE,
  company_id BIGINT NOT NULL REFERENCES rfq_companies(id) ON DELETE CASCADE,
  token TEXT NOT NULL UNIQUE,
  status TEXT NOT NULL DEFAULT 'Sent' CHECK (status IN ('Sent', 'Viewed', 'Quoted', 'Expired')),
  quoted_items INTEGER DEFAULT 0,
  sent_at TIMESTAMPTZ DEFAULT NOW(),
  viewed_at TIMESTAMPTZ,
  submitted_at TIMESTAMPTZ,
  unique_url TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS rfq_quotes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  process_id BIGINT NOT NULL REFERENCES rfq_processes(id) ON DELETE CASCADE,
  company_id BIGINT NOT NULL REFERENCES rfq_companies(id) ON DELETE CASCADE,
  item_id BIGINT NOT NULL REFERENCES rfq_process_items(id) ON DELETE CASCADE,
  price NUMERIC(14,2) NOT NULL,
  attachment_name TEXT,
  attachment_url TEXT,
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(process_id, company_id, item_id)
);

CREATE TABLE IF NOT EXISTS rfq_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  process_id BIGINT NOT NULL REFERENCES rfq_processes(id) ON DELETE CASCADE,
  company_id BIGINT NOT NULL REFERENCES rfq_companies(id) ON DELETE CASCADE,
  author TEXT NOT NULL,
  side TEXT NOT NULL CHECK (side IN ('Buyer', 'Supplier', 'AI')),
  message TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS rfq_notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  process_id BIGINT REFERENCES rfq_processes(id) ON DELETE CASCADE,
  company_id BIGINT REFERENCES rfq_companies(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  message TEXT NOT NULL,
  audience TEXT NOT NULL CHECK (audience IN ('Buyer', 'Supplier')),
  type TEXT NOT NULL CHECK (type IN ('NewProcess', 'Deadline', 'Submission', 'Reminder')),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_rfq_invitations_token ON rfq_invitations(token);
CREATE INDEX IF NOT EXISTS idx_rfq_process_items_process ON rfq_process_items(process_id);
CREATE INDEX IF NOT EXISTS idx_rfq_quotes_process_company ON rfq_quotes(process_id, company_id);
CREATE INDEX IF NOT EXISTS idx_rfq_messages_process_company ON rfq_messages(process_id, company_id);
CREATE INDEX IF NOT EXISTS idx_rfq_notifications_process ON rfq_notifications(process_id);

ALTER TABLE rfq_companies ENABLE ROW LEVEL SECURITY;
ALTER TABLE rfq_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE rfq_processes ENABLE ROW LEVEL SECURITY;
ALTER TABLE rfq_process_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE rfq_invitations ENABLE ROW LEVEL SECURITY;
ALTER TABLE rfq_quotes ENABLE ROW LEVEL SECURITY;
ALTER TABLE rfq_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE rfq_notifications ENABLE ROW LEVEL SECURITY;

CREATE POLICY IF NOT EXISTS "Permitir tudo para rfq_companies" ON rfq_companies FOR ALL USING (true);
CREATE POLICY IF NOT EXISTS "Permitir tudo para rfq_items" ON rfq_items FOR ALL USING (true);
CREATE POLICY IF NOT EXISTS "Permitir tudo para rfq_processes" ON rfq_processes FOR ALL USING (true);
CREATE POLICY IF NOT EXISTS "Permitir tudo para rfq_process_items" ON rfq_process_items FOR ALL USING (true);
CREATE POLICY IF NOT EXISTS "Permitir tudo para rfq_invitations" ON rfq_invitations FOR ALL USING (true);
CREATE POLICY IF NOT EXISTS "Permitir tudo para rfq_quotes" ON rfq_quotes FOR ALL USING (true);
CREATE POLICY IF NOT EXISTS "Permitir tudo para rfq_messages" ON rfq_messages FOR ALL USING (true);
CREATE POLICY IF NOT EXISTS "Permitir tudo para rfq_notifications" ON rfq_notifications FOR ALL USING (true);