-- Execute este script no SQL Editor do seu painel do Supabase para corrigir as tabelas

-- Adicionar coluna de visualizações na tabela de consultas
ALTER TABLE consultas ADD COLUMN IF NOT EXISTS visualizacoes INTEGER DEFAULT 0;

-- Adicionar colunas faltantes na tabela consultas
ALTER TABLE consultas ADD COLUMN IF NOT EXISTS aplicacao TEXT;
ALTER TABLE consultas ADD COLUMN IF NOT EXISTS nome_coloquial TEXT;
ALTER TABLE consultas ADD COLUMN IF NOT EXISTS alterado_por TEXT;
ALTER TABLE consultas ADD COLUMN IF NOT EXISTS data_status TIMESTAMP WITH TIME ZONE;

-- Adicionar coluna de data de indicação na tabela de empresas
ALTER TABLE empresas ADD COLUMN IF NOT EXISTS data_indicacao TIMESTAMP WITH TIME ZONE DEFAULT NOW();

-- Adicionar coluna nome_usuario na tabela auditoria
ALTER TABLE auditoria ADD COLUMN IF NOT EXISTS nome_usuario TEXT;

-- Adicionar colunas faltantes na tabela amizades
ALTER TABLE amizades ADD COLUMN IF NOT EXISTS id BIGINT GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE amizades ADD COLUMN IF NOT EXISTS status TEXT CHECK(status IN ('pendente', 'aceito')) DEFAULT 'pendente';
ALTER TABLE amizades DROP CONSTRAINT IF EXISTS amizades_pkey;
ALTER TABLE amizades ADD CONSTRAINT amizades_pkey PRIMARY KEY (id);
ALTER TABLE amizades ADD CONSTRAINT amizades_unique UNIQUE (usuario_id, amigo_id);

-- Garantir que as tabelas de amizade e notificações tenham as permissões corretas (caso RLS esteja ativo)
-- (Opcional, pois o backend agora usa a chave de serviço para contornar, mas é bom ter)
-- Nota: As políticas abaixo podem já existir. Se der erro, ignore ou execute separadamente com DROP IF EXISTS.
-- ALTER TABLE amizades ENABLE ROW LEVEL SECURITY;
-- CREATE POLICY "Permitir tudo para amizades" ON amizades FOR ALL USING (true);

-- ALTER TABLE notificacoes ENABLE ROW LEVEL SECURITY;
-- CREATE POLICY "Permitir tudo para notificacoes" ON notificacoes FOR ALL USING (true);
